site_name: OBA documentation
nav:
  - Mapping: mapping.md
  - Implementations: implementations.md
theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
